[windows_2025]
windows-server-2025 ansible_host=172.30.96.1 ansible_port=2200

[windows_2025:vars]
ansible_connection=ssh
ansible_user=Administrador
ansible_shell_type=powershell
ansible_shell_executable=powershell.exe
